### ISSUE TITLE
2.6.1 video recording failed (cairo.Error: invalid value (typically too big))

### ISSUE THREAD

**Issue by hostbbb** [bigbluebutton/bbb-presentation-video#40]
2.6.1 video recording failed (cairo.Error: invalid value (typically too big))
```
I, [2023-04-07T10:59:15.010155 #3536697]  INFO -- :     Presentation: pan: [0.000,0.000] zoom: 0.010x0.010
I, [2023-04-07T10:59:15.010176 #3536697]  INFO -- :     Presentation: padding: 0.000x90.003
I, [2023-04-07T10:59:15.010194 #3536697]  INFO -- :     Presentation: slide size: 19.899x11.193, scale: 48.244236, position: [-0.000,-0.000]]
I, [2023-04-07T10:59:15.010214 #3536697]  INFO -- :     Presentation: slide scaled size: 960.000x539.994
I, [2023-04-07T10:59:15.010232 #3536697]  INFO -- :     Presentation: shapes size: 2048.000x1152.000, scale: 0.937500
I, [2023-04-07T10:59:15.287457 #3536697]  INFO -- : Traceback (most recent call last):
I, [2023-04-07T10:59:15.287535 #3536697]  INFO -- :   File "/usr/bin/bbb-presentation-video", line 11, in <module>
I, [2023-04-07T10:59:15.287554 #3536697]  INFO -- :     load_entry_point('bbb-presentation-video==4.0.1', 'console_scripts', 'bbb-presentation-video')()
I, [2023-04-07T10:59:15.287573 #3536697]  INFO -- :   File "/usr/share/bbb-presentation-video/bbb_presentation_video/__init__.py", line 164, in main
I, [2023-04-07T10:59:15.287590 #3536697]  INFO -- :     renderer.render()
I, [2023-04-07T1
[3b0d676c53d544e4437850a1fd74757e053bbca8-1680858052156-events.xml.txt]
0:59:15.287608 #3536697]  INFO -- :   File "/usr/share/bbb-presentation-video/bbb_presentation_video/renderer/__init__.py", line 297, in render
I, [2023-04-07T10:59:15.287625 #3536697]  INFO -- :     presentation_changed = presentation.finalize_frame()
I, [2023-04-07T10:59:15.287642 #3536697]  INFO -- :   File "/usr/share/bbb-presentation-video/bbb_presentation_video/renderer/presentation.py", line 354, in finalize_frame
I, [2023-04-07T10:59:15.287659 #3536697]  INFO -- :     pdfSurface = cairo.ImageSurface(
I, [2023-04-07T10:59:15.287676 #3536697]  INFO -- : cairo.Error: invalid value (typically too big) for the size of the input (surface, pattern, etc.)
I, [2023-04-07T10:59:15.436224 #3536697]  INFO -- : Success?: false
I, [2023-04-07T10:59:15.436308 #3536697]  INFO -- : Process exited? true
I, [2023-04-07T10:59:15.436329 #3536697]  INFO -- : Exit status: 1
```
events.xml attached, can provide complete raw archive if needed.
(https://github.com/bigbluebutton/bbb-presentation-video/files/11183119/3b0d676c53d544e4437850a1fd74757e053bbca8-1680858052156-events.xml.txt)

**Comment by ffdixon** [comment]
Just did a quick test and was able to install a new BigBlueButton 2.6 + bbb-presentation-video and it generated video files for the recoridngs.

<img width="1156" alt="image" src="https://user-images.githubusercontent.com/290351/230736523-f1364b8f-36b0-488f-b009-161ee47b01a9.png">

However, there might be some sequence of shapes in your recording that has tripped up the generation of playback.

**Comment by hostbbb** [comment]
yes, converters working good..  doing about 500 a day successfully.  just going to open issues with any edge cases and events.xml.
have raw archives if also needed.

**Comment by hostbbb** [comment]
[3b0d676c53d544e4437850a1fd74757e053bbca8-1680858052156-presentation.tar.gz](https://github.com/bigbluebutton/bbb-presentation-video/files/11194021/3b0d676c53d544e4437850a1fd74757e053bbca8-1680858052156-presentation.tar.gz)
